name: Piven.TECH
markdown: kramdown
permalink: /blog/:year/:month/:day/:title/
excerpt_separator: <!--more-->
paginate: 36
paginate_path: "/blog/page/num/"
plugins:
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
