name: Piven.TECH
markdown: kramdown
permalink: /blog/:year/:month/:day/:title/
excerpt_separator: <!--more-->
plugins:
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
paginate: 12
paginate_path: "/blog/page/:num/"
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
collections:
  posts:
    output: false
    sort_by: date
  video:
    output: false
    sort_by: date
  audio:
    output: false
    sort_by: date
  texts:
    output: false
    sort_by: date
