name: Piven.TECH
markdown: kramdown

collections:
  contributions:
    output: false

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

google_analytics: G-D13H3023Z7
